apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: idp

  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: "1.9.6"
      helm:
        releaseName: backstage
        valueFiles:
          - $values/helm-values/backstage/base.yaml
    - repoURL: https://github.com/cokee96/backstage-idp
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: backstage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
